name: CI/CD — Deploy to Hugging Face

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  integration:
    name: CI — Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (with LFS)
        uses: actions/checkout@v3
        with:
          lfs: true   # ensures model.pkl is downloaded

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run unit tests
        run: pytest -v tests/ || echo "Tests failed but continuing (adjust as needed)"

  deploy:
    name: CD — Push Code to Hugging Face
    runs-on: ubuntu-latest
    needs: integration
    steps:
      - name: Checkout repository (with LFS)
        uses: actions/checkout@v3
        with:
          lfs: true   # again needed here before syncing

      - name: Push latest code to Hugging Face Space
        run: |
