name: CI/CD — Deploy to Hugging Face

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  integration:
    name: CI — Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install dagshub

      - name: Run unit tests
        run: pytest tests/

  build_and_push_docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: integration
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          # Build public image by default
          docker build -t ${{ secrets.DOCKER_USERNAME }}/customer_churn_app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/customer_churn_app:latest

          # For private image (comment out above and uncomment below when needed)
          # docker build -t ${{ secrets.DOCKER_USERNAME }}/customer_churn_app:private .
          # docker push ${{ secrets.DOCKER_USERNAME }}/customer_churn_app:private

  deploy:
    name: CD — Trigger Hugging Face Deployment
    runs-on: ubuntu-latest
    needs: build_and_push_docker
    steps:
      - name: Checkout Hugging Face Space
        run: |
          git clone https://huggingface.co/spaces/NihalNiair/customer_churn_app space_repo
          cd space_repo
          
          # Public image configuration
          echo "FROM ${{ secrets.DOCKER_USERNAME }}/customer_churn_app:latest" > Dockerfile
          
          # For private image (uncomment above and comment below when needed)
          # echo "FROM ${{ secrets.DOCKER_USERNAME }}/customer_churn_app:private" > Dockerfile
          # echo "ARG DOCKER_USERNAME" >> Dockerfile
          # echo "ARG DOCKER_PASSWORD" >> Dockerfile
          # echo "RUN echo \"$DOCKER_PASSWORD\" | docker login -u \"$DOCKER_USERNAME\" --password-stdin" >> Dockerfile

          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USERNAME }}"
          git add Dockerfile
          git commit -m "Update Dockerfile to pull latest image"
          git push https://NihalNiair:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/NihalNiair/customer_churn_app main