name: CI/CD — Deploy to Hugging Face via Docker Image

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  integration:
    name: CI — Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install dagshub

      - name: Run unit tests
        run: pytest tests/

  build_and_push_docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: integration
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/customer_churn_app:latest .

      - name: Push Docker image (public or private depending on Docker Hub repo settings)
        run: docker push ${{ secrets.DOCKER_USERNAME }}/customer_churn_app:latest

      # Optional: Push a private-tagged version
      # - name: Push private-tagged image
      #   run: docker push ${{ secrets.DOCKER_USERNAME }}/private_customer_churn_app:latest

  deploy:
    name: CD — Trigger Hugging Face Deployment
    runs-on: ubuntu-latest
    needs: build_and_push_docker
    steps:
      - name: Checkout Hugging Face Space
        run: |
          git clone https://huggingface.co/spaces/NihalNiair/customer_churn_app space_repo
          cd space_repo
          echo "FROM docker.io/${{ secrets.DOCKER_USERNAME }}/customer_churn_app:latest" > Dockerfile
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USERNAME }}"
          git add Dockerfile
          git commit -m "Update Dockerfile to pull latest image"
          git push https://NihalNiair:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/NihalNiair/customer_churn_app main
